# ███████╗██╗     ██╗███████╗██╗███████╗██╗   ██╗
# ██╔════╝██║     ██║╚══███╔╝██║██╔════╝╚██╗ ██╔╝
# █████╗  ██║     ██║  ███╔╝ ██║█████╗   ╚████╔╝ 
# ██╔══╝  ██║     ██║ ███╔╝  ██║██╔══╝    ╚██╔╝  
# ███████╗███████╗██║███████╗██║██║        ██║   
# ╚══════╝╚══════╝╚═╝╚══════╝╚═╝╚═╝        ╚═╝   
#
# Deploy elizaOS anywhere
# https://github.com/bealers/elizify
#
services:
  eliza-slim:
    build:
      context: .
      dockerfile: Dockerfile
      target: slim  # Use slim build stage
    container_name: elizaos-slim
    restart: unless-stopped
    ports:
      - "3000:3000"  # Slim environment port

    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      # ELIZA_UI_ENABLE: unset - auto-detects from NODE_ENV
      POSTGRES_URL: ${POSTGRES_URL:-postgresql://eliza:eliza_password@localhost:5432/eliza}

      # Authentication - Production default (secure by default, respects empty)
      ELIZA_SERVER_AUTH_TOKEN: ${ELIZA_SERVER_AUTH_TOKEN-production-token}

      # Additional configurable settings
      HOST: 0.0.0.0
      API_PORT: 3000
      CHARACTER_FILE: /app/config/characters/server-bod.character.json

      # Performance settings
      MAX_MEMORY_USAGE: 1024
      RATE_LIMIT_REQUESTS: 1000
      RATE_LIMIT_WINDOW: 900000

    volumes:
      - eliza_slim_data:/app/data
      - eliza_slim_logs:/app/logs
      - ./config/characters:/app/characters:ro

    networks:
      - elizaos_network

    # Same resource limits as full target
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/agents"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 45s

volumes:
  eliza_slim_data:
    driver: local
  eliza_slim_logs:
    driver: local

networks:
  elizaos_network:
    name: elizaos_network
    external: true