# ███████╗██╗     ██╗███████╗██╗███████╗██╗   ██╗
# ██╔════╝██║     ██║╚══███╔╝██║██╔════╝╚██╗ ██╔╝
# █████╗  ██║     ██║  ███╔╝ ██║█████╗   ╚████╔╝ 
# ██╔══╝  ██║     ██║ ███╔╝  ██║██╔══╝    ╚██╔╝  
# ███████╗███████╗██║███████╗██║██║        ██║   
# ╚══════╝╚══════╝╚═╝╚══════╝╚═╝╚═╝        ╚═╝   
#
# Deploy elizaOS anywhere
# https://github.com/bealers/elizify
#
services:
  elizaos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elizaos
    ports:
      - "3000:3000"  # Full environment port
    depends_on:
      elizaos-db:
        condition: service_healthy

    environment:
      NODE_ENV: production
      LOG_LEVEL: info
      # ELIZA_UI_ENABLE: unset - auto-detects from NODE_ENV

      # Database connection
      POSTGRES_URL: postgresql://eliza:eliza_password@elizaos-db:5432/eliza_test

      # Additional configurable settings
      HOST: 0.0.0.0
      API_PORT: 3000
      CHARACTER_FILE: /app/config/characters/server-bod.character.json

      # Performance settings
      MAX_MEMORY_USAGE: 1024
      RATE_LIMIT_REQUESTS: 1000
      RATE_LIMIT_WINDOW: 900000

    volumes:
      - eliza_data:/app/data
      - eliza_logs:/app/logs
      - ./config/characters:/app/characters:ro

    networks:
      - elizaos_network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/agents"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 45s

  elizaos-db:
    image: ankane/pgvector:latest
    container_name: elizaos-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: eliza_test
      POSTGRES_USER: eliza
      POSTGRES_PASSWORD: eliza_password
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      POSTGRES_MAX_CONNECTIONS: 200

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

    ports:
      - "5432:5432"

    networks:
      - elizaos_network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eliza -d eliza_test"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  eliza_data:
    driver: local
  eliza_logs:
    driver: local
  postgres_data:
    driver: local

networks:
  elizaos_network:
    name: elizaos_network
    external: true